name: generate ascii
on: push

jobs:
    first_job: 
      runs-on: ubuntu-latest
      steps: 
      - name: checkout repo
        uses: actions/checkout@v4

      - name: list file
        run: ls -ltra

      - name: Excuting shell script
        run: |
            chmod +x ascii-script.sh
            ./ascii-script.sh

      
